ProductionID: WFD_3
Instrument:
   name : LSST       #name of the telescope (internal)
   throughput_dir : LSST_THROUGHPUTS_BASELINE #dir of throughput
   atmos_dir : THROUGHPUTS_DIR   #dir of atmos
   airmass : 1.1   #airmass value
   atmos : True  #atmos
   aerosol : False  #aerosol
Simulations: 
   filename: Simu_WFD_3.hdf5   # Name of simulation  file
   dirname : ../Output_Simu/colossus_2665/WFD       # dir of obs file
Fitter:
    name : SN_Cosmo           # Simulator name: SN_Cosmo,SN_Sim,SN_Ana
    model : salt2-extended   # spectra model
    version : 1.0                     #version
Display : False  #display during LC fit
Output:
    directory: Output_Fit/colossus_2665/WFD
    save: True