ProductionID: alt_sched_1
Instrument:
   name : LSST       #name of the telescope (internal)
   throughput_dir : LSST_THROUGHPUTS_BASELINE #dir of throughput
   atmos_dir : THROUGHPUTS_DIR   #dir of atmos
   airmass : 1.1   #airmass value
   atmos : True  #atmos
   aerosol : False  #aerosol
Simulations: 
   filename: Simu_alt_sched_1.hdf5   # Name of simulation  file
   dirname : /sps/lsst/users/gris/Output_Simu_pipeline_test     # dir of obs file
Fitter:
    name : fitter.SN_Cosmo           # Simulator name: SN_Cosmo,SN_Sim,SN_Ana
    model : salt2-extended   # spectra model
    version : 1.0                     #version
Display : False  #display during LC fit
Output:
    directory: /sps/lsst/users/gris/Output_Fit_test/
    save: True
Multiprocessing:
    nproc: 1